"""empty message

Revision ID: b7388770b630
Revises: 
Create Date: 2022-05-26 20:42:54.652587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7388770b630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('okpo', sa.String(length=10), nullable=True),
    sa.Column('off_address', sa.String(), nullable=True),
    sa.Column('post_address', sa.String(), nullable=True),
    sa.Column('head_position', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('patronymic', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('accounting', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_accounting'), 'organization', ['accounting'], unique=False)
    op.create_index(op.f('ix_organization_email'), 'organization', ['email'], unique=True)
    op.create_index(op.f('ix_organization_first_name'), 'organization', ['first_name'], unique=False)
    op.create_index(op.f('ix_organization_fullname'), 'organization', ['fullname'], unique=True)
    op.create_index(op.f('ix_organization_inn'), 'organization', ['inn'], unique=True)
    op.create_index(op.f('ix_organization_last_name'), 'organization', ['last_name'], unique=False)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_index(op.f('ix_organization_off_address'), 'organization', ['off_address'], unique=False)
    op.create_index(op.f('ix_organization_patronymic'), 'organization', ['patronymic'], unique=False)
    op.create_index(op.f('ix_organization_post_address'), 'organization', ['post_address'], unique=False)
    op.create_table('typecontract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typename', sa.String(length=64), nullable=True),
    sa.Column('we_sell', sa.Boolean(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typecontract_typename'), 'typecontract', ['typename'], unique=True)
    op.create_index(op.f('ix_typecontract_we_sell'), 'typecontract', ['we_sell'], unique=False)
    op.create_table('typefulfillment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typename', sa.String(length=64), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typefulfillment_typename'), 'typefulfillment', ['typename'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('typefulfillment_id', sa.Integer(), nullable=True),
    sa.Column('accounting_method', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('contractor', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contractor'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['typecontract.id'], ),
    sa.ForeignKeyConstraint(['typefulfillment_id'], ['typefulfillment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_date'), 'contract', ['date'], unique=False)
    op.create_index(op.f('ix_contract_full_name'), 'contract', ['full_name'], unique=False)
    op.create_index(op.f('ix_contract_name'), 'contract', ['name'], unique=False)
    op.create_index(op.f('ix_contract_number'), 'contract', ['number'], unique=False)
    op.create_index(op.f('ix_contract_price'), 'contract', ['price'], unique=False)
    op.create_table('fulfillment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_date'), 'fulfillment', ['date'], unique=False)
    op.create_index(op.f('ix_fulfillment_number'), 'fulfillment', ['number'], unique=False)
    op.create_index(op.f('ix_fulfillment_price'), 'fulfillment', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fulfillment_price'), table_name='fulfillment')
    op.drop_index(op.f('ix_fulfillment_number'), table_name='fulfillment')
    op.drop_index(op.f('ix_fulfillment_date'), table_name='fulfillment')
    op.drop_table('fulfillment')
    op.drop_index(op.f('ix_contract_price'), table_name='contract')
    op.drop_index(op.f('ix_contract_number'), table_name='contract')
    op.drop_index(op.f('ix_contract_name'), table_name='contract')
    op.drop_index(op.f('ix_contract_full_name'), table_name='contract')
    op.drop_index(op.f('ix_contract_date'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_typefulfillment_typename'), table_name='typefulfillment')
    op.drop_table('typefulfillment')
    op.drop_index(op.f('ix_typecontract_we_sell'), table_name='typecontract')
    op.drop_index(op.f('ix_typecontract_typename'), table_name='typecontract')
    op.drop_table('typecontract')
    op.drop_index(op.f('ix_organization_post_address'), table_name='organization')
    op.drop_index(op.f('ix_organization_patronymic'), table_name='organization')
    op.drop_index(op.f('ix_organization_off_address'), table_name='organization')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_last_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_inn'), table_name='organization')
    op.drop_index(op.f('ix_organization_fullname'), table_name='organization')
    op.drop_index(op.f('ix_organization_first_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_email'), table_name='organization')
    op.drop_index(op.f('ix_organization_accounting'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
